# Generated by Django 2.2 on 2020-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(to='todos.Language'),
        ),
    ]
